modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/mergerfs/repo/fedora-39/errornointernet-mergerfs-fedora-39.repo
    install:
      # essentials
      - bat
      - etckeeper
      - eza
      - tailscale
      - zsh
      # # virtualization
      - guestfs-tools
      - libvirt
      - virt-install
      # server
      - mergerfs
      - samba
      - snapraid

  - type: systemd
    system:
      enabled:
        - tailscaled
        - libvirtd

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
